---
collections:
  skills:

include: [".well-known/brave-rewards-verification.txt"]

defaults:
  - scope:
      path: ""  # an empty string here means all files in the project
    values:
      layout: "default"
